### ISSUE TITLE
onReachBottom只能触发一次？

### ISSUE THREAD

**Issue by kkkisme** [ikcamp/wechat-xcx-tutorial#21]

**Comment by BruceCham** [comment]
@Joker09   
onReachBottom 这个是微信小程序内置的监听回调函数，只要到达页面底部就会触发，不限次数。在本教程里面，触发后的回调加有业务逻辑：
```js
onReachBottom () {
        if (this.data.hasMore) {
            let nextPage = this.data.page + 1;
            this.setData({
                page: nextPage
            });
            this.requestArticle();
        }
    },   
```
如果 `hasMore` 标识为 false，就代表不需要再加载内容了

**Comment by kkkisme** [comment]
@brucecham 不知道什么原因，就算我只在onReachBottom只打印一句log，并且将page设为`height:100%`,然后不断上拉页面，也只会打印一次

**Comment by BruceCham** [comment]
@Joker09 分支 `ch3-4` 讲的是下拉更新，`ch4-1` 是 `ch3-4` 讲完后的完整代码，你可以切换到ch4-1，把`code/` 导入到开发工具试试，对比下。我刚试了下，可以无限触发。实在不行的话，你可以把代码贴出来看看

**Comment by kkkisme** [comment]
```
// pages/list/list.js
Page({

onReachBottom(){
  console.log('触发');
}

})
```
```
<!--pages/list/list.wxml-->
<view class="classname">page</view>
```

```
/* pages/list/list.wxss */
page{
  height: 100%;
}
```

**Comment by Tinyuen** [comment]
@Joker09  list.wxml 页面的实际高度是多少？onReachBottom 因该是上拉触底才会触发，100%高度页面满屏不存在上拉可能，你尝试将页面内容超过一屏在上拉试试

**Comment by kkkisme** [comment]
@Tinyuen  好像是这样的，但也不是完全不能触发，第一次可以触发。这完全是个黑盒子，像页面没有内容算是极端情况吧。thx

**Comment by Tinyuen** [comment]
@Joker09  嗯嗯  微信坑多，多踩踩就知道了
