### ISSUE TITLE
token过期如何自动重新发起请求

### ISSUE THREAD

**Issue by iijx** [ikcamp/wechat-xcx-tutorial#24]
大神们好，，请教个小程序里的问题：

小程序中的wx.login拿到code, 用code向后台换取 token,  那么在网络请求中遇到 token 过期的情况，需要重新走一遍登录流程拿到新的 token，并带着新 token 重新请求。这里如何实现。
`
util. request({
    url: '',
    data: {},
}).then( (res) => {
    if(  res.error && "token过期" ) { ??? } // 请求发生错误并且错误类型是 token 过期，这里如何重新发起这次请求。
})
`

**Comment by pangz1** [comment]
如果token过期，需要重新调用wx.login获取code，然后用code换取token，再用新的token去做你要做的事情

**Comment by iijx** [comment]
对，流程明白了，就是，如果每次request请求都，要在succeess函数中进行token的判断，并对token过期的情况进行这样额外处理的过程，感觉很麻烦呀～，因为基本每个请求都要涉及这个处理过程。

如果把这个处理过程封装进 _request 中，如果 token 过期就自动地走流程，并自动带着新 token 去重新请求。

这样是不是更好呀！

**Comment by pangz1** [comment]
对，这样建议封装起来，尽量少的重复
