### ISSUE TITLE
请问有组件开发的内容讲解吗

### ISSUE THREAD

**Issue by arronf2e** [ikcamp/wechat-xcx-tutorial#25]
对小程序的组件封装有点兴趣，正在学习，想问下有没有这方面的分享

**Comment by BruceCham** [comment]
@arronf2e 
最近会有一次线下的沙龙活动分享，可以互动交流 [小程序活动行](http://officialikcamp.huodongxing.com/go/ikcampwechat?utm_source=%E4%B8%BB%E5%8A%9E%E6%96%B9%E9%A1%B5&utm_medium=&utm_campaign=orgpage)

**Comment by arronf2e** [comment]
@BruceCham ok，可以
